[project]
name = "port"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "dj-database-url>=3.1.0",
    "django>=6.0.1",
    "gunicorn>=24.1.1",
    "python-dotenv>=1.2.1",
    "whitenoise>=6.11.0",
]
